name: 'ucando'
version: '1.0.0'
config-version: 2

profile: 'ucando'

model-paths: ["models"]
test-paths: ["tests"]

models:
  ucando:
    staging:
      +materialized: view

    intermediate:
      +materialized: table

    marts:
      +materialized: table